FROM python:3.11

COPY mcp_server /src/mcp_server
WORKDIR /src
RUN pip install -r mcp_server/requirements.txt

EXPOSE 8000
CMD ["fastmcp", "run", "mcp_server/server.py:mcp", "--transport", "http", "--port", "8000", "--host", "0.0.0.0"]