FROM python:3.11

RUN apt-get update && apt-get install -y cmake make g++
COPY mcp /src/mcp
WORKDIR /src
RUN pip install -r mcp/requirements.txt

EXPOSE 8000
CMD ["fastmcp", "run", "mcp/server.py:mcp", "--transport", "http", "--port", "8000", "--host", "0.0.0.0"]